# Internal routing configuration to handle ESI
#_internal:
#   resource: "@FrameworkBundle/Resources/config/routing/internal.xml"
#   prefix:   /_internal

KhepinGolfBundle:
  resource: "@KhepinGolfBundle/Controller/HelloController.php"
  type:     annotation
  prefix:   /