<?php

namespace Khepin\StoreBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * ProductRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ProductRepository extends EntityRepository
{
    
    public function findFirst(){
        return $this->findOneById(1);
    }
}